version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Sdc.DevOps.Sample.Api.Core.sln && dotnet publish ./Sdc.DevOps.Sample.Api.Core.sln -c Release -o ./obj/Docker/publish"
